#!/usr/bin/env php

<?php

if ('cli' !== php_sapi_name()) {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use Clipper\Console;

$console = new Console();

$console->registerController('hello', new \Console\Command\HelloController($console));

$console->registerCommand('help', function (array $argv) use ($console) {
    Console::print("usage: clipper hello [ your-name ]");
});

$console->runCommand($argv);
