#!/usr/bin/env php

<?php

if ('cli' !== php_sapi_name()) {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use Clipper\CommandCall;
use Clipper\Console;

$console = new Console();
$console->setSignature("clipper hello name [ user=name ]");

$console->registerCommand('hello', function (CommandCall $call) use ($console) {
    $console->printSignature();
    var_dump($call->params);
});

$console->runCommand($argv);
